<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Property;

class ArabicPropertiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $properties = [
            [
                'title' => 'شقة فاخرة في التجمع الخامس',
                'description' => 'شقة فاخرة بمساحة 180 متر مربع، 3 غرف نوم، 2 حمام، صالة واسعة، مطبخ أمريكي، تشطيب سوبر لوكس، في كمبوند راقي بالتجمع الخامس',
                'type' => 'apartment',
                'status' => 'available',
                'listing_type' => 'sale',
                'price' => 3500000,
                'area' => 180,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'parking_spaces' => 2,
                'floor_number' => 5,
                'total_floors' => 12,
                'year_built' => 2022,
                'furnished' => true,
                'amenities' => ['مسبح', 'نادي رياضي', 'حراسة 24 ساعة', 'حدائق'],
                'address' => 'كمبوند ماونتن فيو، التجمع الخامس',
                'city' => 'القاهرة الجديدة',
                'state' => 'القاهرة',
                'country' => 'مصر',
                'postal_code' => '11835',
                'reference_number' => 'AR-PROP-001',
                'notes' => 'شقة بإطلالة رائعة على المساحات الخضراء، جاهزة للسكن',
                'assigned_to' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'images' => ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2'],
            ],
            [
                'title' => 'فيلا مستقلة في الشيخ زايد',
                'description' => 'فيلا فخمة بتصميم معماري حديث، 4 غرف نوم رئيسية، 5 حمامات، غرفة معيشة كبيرة، مطبخ إيطالي، حديقة خاصة، حمام سباحة',
                'type' => 'villa',
                'status' => 'available',
                'listing_type' => 'sale',
                'price' => 8500000,
                'area' => 400,
                'bedrooms' => 4,
                'bathrooms' => 5,
                'parking_spaces' => 3,
                'floor_number' => null,
                'total_floors' => 3,
                'year_built' => 2023,
                'furnished' => false,
                'amenities' => ['حمام سباحة', 'حديقة', 'غرفة خادمة', 'سينما منزلية'],
                'address' => 'بيفرلي هيلز، الشيخ زايد',
                'city' => 'الشيخ زايد',
                'state' => 'الجيزة',
                'country' => 'مصر',
                'postal_code' => '12588',
                'reference_number' => 'AR-PROP-002',
                'notes' => 'فيلا في موقع مميز، قريبة من جميع الخدمات',
                'assigned_to' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'images' => ['https://images.unsplash.com/photo-1613490493576-7fde63acd811', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750'],
            ],
            [
                'title' => 'شقة للإيجار في المعادي',
                'description' => 'شقة مفروشة للإيجار في المعادي، 2 غرفة نوم، حمام، صالة، مطبخ مجهز بالكامل، قريبة من المترو والخدمات',
                'type' => 'apartment',
                'status' => 'available',
                'listing_type' => 'rent',
                'price' => 8000,
                'area' => 120,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'parking_spaces' => 1,
                'floor_number' => 3,
                'total_floors' => 8,
                'year_built' => 2020,
                'furnished' => true,
                'amenities' => ['أسانسير', 'أمن', 'قريب من المترو'],
                'address' => 'شارع 9، المعادي',
                'city' => 'المعادي',
                'state' => 'القاهرة',
                'country' => 'مصر',
                'postal_code' => '11728',
                'reference_number' => 'AR-PROP-003',
                'notes' => 'شقة نظيفة ومجهزة، مناسبة للعائلات والأفراد',
                'assigned_to' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'images' => ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688', 'https://images.unsplash.com/photo-1493809842364-78817add7ffb'],
            ],
            [
                'title' => 'بنتهاوس فاخر في الزمالك',
                'description' => 'بنتهاوس فريد بإطلالة بانورامية على النيل، 300 متر + 150 متر تراس، 3 غرف نوم ماستر، 4 حمامات، تشطيب فاخر جداً',
                'type' => 'penthouse',
                'status' => 'pending',
                'listing_type' => 'sale',
                'price' => 12000000,
                'area' => 300,
                'bedrooms' => 3,
                'bathrooms' => 4,
                'parking_spaces' => 2,
                'floor_number' => 15,
                'total_floors' => 15,
                'year_built' => 2021,
                'furnished' => true,
                'amenities' => ['تراس', 'إطلالة على النيل', 'جاكوزي', 'نظام منزل ذكي'],
                'address' => 'شارع البرازيل، الزمالك',
                'city' => 'الزمالك',
                'state' => 'القاهرة',
                'country' => 'مصر',
                'postal_code' => '11211',
                'reference_number' => 'AR-PROP-004',
                'notes' => 'بنتهاوس استثنائي في أرقى أحياء القاهرة',
                'assigned_to' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'images' => ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00', 'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e'],
            ],
            [
                'title' => 'دوبلكس في 6 أكتوبر',
                'description' => 'دوبلكس واسع 250 متر، 4 غرف نوم، 3 حمامات، صالتين، مطبخ كبير، تراس، في كمبوند مغلق مع جميع الخدمات',
                'type' => 'duplex',
                'status' => 'available',
                'listing_type' => 'sale',
                'price' => 4200000,
                'area' => 250,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'parking_spaces' => 2,
                'floor_number' => 1,
                'total_floors' => 2,
                'year_built' => 2022,
                'furnished' => false,
                'amenities' => ['حراسة', 'مسبح', 'ملاعب', 'مول تجاري'],
                'address' => 'كمبوند دريم لاند، 6 أكتوبر',
                'city' => '6 أكتوبر',
                'state' => 'الجيزة',
                'country' => 'مصر',
                'postal_code' => '12573',
                'reference_number' => 'AR-PROP-005',
                'notes' => 'موقع استراتيجي قريب من مول العرب وهايبر وان',
                'assigned_to' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'images' => ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c'],
            ],
            [
                'title' => 'أرض للبيع في العاصمة الإدارية',
                'description' => 'أرض سكنية في موقع مميز بالعاصمة الإدارية الجديدة، 500 متر مربع، على شارع رئيسي، جميع المرافق متوفرة',
                'type' => 'land',
                'status' => 'available',
                'listing_type' => 'sale',
                'price' => 5000000,
                'area' => 500,
                'bedrooms' => null,
                'bathrooms' => null,
                'parking_spaces' => null,
                'floor_number' => null,
                'total_floors' => null,
                'year_built' => null,
                'furnished' => false,
                'amenities' => ['مرافق متوفرة', 'شارع رئيسي'],
                'address' => 'الحي السكني R7، العاصمة الإدارية',
                'city' => 'العاصمة الإدارية',
                'state' => 'القاهرة',
                'country' => 'مصر',
                'postal_code' => '11566',
                'reference_number' => 'AR-PROP-006',
                'notes' => 'فرصة استثمارية ممتازة في قلب العاصمة الجديدة',
                'assigned_to' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'images' => ['https://images.unsplash.com/photo-1500382017468-9049fed747ef', 'https://images.unsplash.com/photo-1464146072230-91cabc968266'],
            ],
            [
                'title' => 'استوديو مفروش في الشروق',
                'description' => 'استوديو عصري ومفروش بالكامل، مساحة 60 متر، غرفة واحدة، حمام، ركن مطبخ أمريكي، مثالي للشباب والمغتربين',
                'type' => 'studio',
                'status' => 'rented',
                'listing_type' => 'rent',
                'price' => 3500,
                'area' => 60,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'parking_spaces' => 1,
                'floor_number' => 7,
                'total_floors' => 10,
                'year_built' => 2021,
                'furnished' => true,
                'amenities' => ['واي فاي', 'أمن', 'قريب من الخدمات'],
                'address' => 'المنطقة الثانية، الشروق',
                'city' => 'الشروق',
                'state' => 'القاهرة',
                'country' => 'مصر',
                'postal_code' => '11837',
                'reference_number' => 'AR-PROP-007',
                'notes' => 'مؤجر حالياً، متاح من الشهر القادم',
                'assigned_to' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'images' => ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af', 'https://images.unsplash.com/photo-1560448204-603b3fc33ddc'],
            ],
            [
                'title' => 'شاليه في الساحل الشمالي',
                'description' => 'شاليه رائع في قرية سياحية راقية بالساحل الشمالي، 100 متر + جاردن 50 متر، غرفتين نوم، 2 حمام، إطلالة على البحر',
                'type' => 'townhouse',
                'status' => 'available',
                'listing_type' => 'sale',
                'price' => 2800000,
                'area' => 100,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'parking_spaces' => 1,
                'floor_number' => null,
                'total_floors' => 1,
                'year_built' => 2020,
                'furnished' => true,
                'amenities' => ['شاطئ خاص', 'حمامات سباحة', 'مطاعم', 'أمن'],
                'address' => 'قرية مراسي، الساحل الشمالي',
                'city' => 'الساحل الشمالي',
                'state' => 'مطروح',
                'country' => 'مصر',
                'postal_code' => '51511',
                'reference_number' => 'AR-PROP-008',
                'notes' => 'شاليه جاهز للاستخدام، بإطلالة مباشرة على البحر',
                'assigned_to' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'images' => ['https://images.unsplash.com/photo-1499793983690-e29da59ef1c2', 'https://images.unsplash.com/photo-1566073771259-6a8506099945'],
            ],
            [
                'title' => 'مكتب إداري في المهندسين',
                'description' => 'مكتب تجاري في برج إداري بالمهندسين، 150 متر، 3 غرف، ريسبشن، حمام، تشطيب ممتاز، مناسب لجميع الأنشطة',
                'type' => 'office',
                'status' => 'available',
                'listing_type' => 'rent',
                'price' => 15000,
                'area' => 150,
                'bedrooms' => null,
                'bathrooms' => 1,
                'parking_spaces' => 2,
                'floor_number' => 8,
                'total_floors' => 12,
                'year_built' => 2019,
                'furnished' => false,
                'amenities' => ['مصاعد حديثة', 'أمن', 'مولد كهرباء', 'تكييف مركزي'],
                'address' => 'شارع جامعة الدول العربية، المهندسين',
                'city' => 'المهندسين',
                'state' => 'الجيزة',
                'country' => 'مصر',
                'postal_code' => '12411',
                'reference_number' => 'AR-PROP-009',
                'notes' => 'موقع حيوي في قلب المهندسين، قريب من المترو',
                'assigned_to' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'images' => ['https://images.unsplash.com/photo-1497366216548-37526070297c', 'https://images.unsplash.com/photo-1497366811353-6870744d04b2'],
            ],
            [
                'title' => 'محل تجاري في وسط البلد',
                'description' => 'محل تجاري على شارع رئيسي في وسط البلد، مساحة 80 متر، واجهة زجاجية كبيرة، مناسب لجميع الأنشطة التجارية',
                'type' => 'commercial',
                'status' => 'sold',
                'listing_type' => 'sale',
                'price' => 3500000,
                'area' => 80,
                'bedrooms' => null,
                'bathrooms' => 1,
                'parking_spaces' => null,
                'floor_number' => null,
                'total_floors' => null,
                'year_built' => 2015,
                'furnished' => false,
                'amenities' => ['واجهة زجاجية', 'شارع رئيسي', 'حركة تجارية عالية'],
                'address' => 'شارع طلعت حرب، وسط البلد',
                'city' => 'وسط البلد',
                'state' => 'القاهرة',
                'country' => 'مصر',
                'postal_code' => '11511',
                'reference_number' => 'AR-PROP-010',
                'notes' => 'تم البيع - محل في موقع استراتيجي ممتاز',
                'assigned_to' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'images' => ['https://images.unsplash.com/photo-1441986300917-64674bd600d8', 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d'],
            ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}
